### ISSUE TITLE
OpNode Image Logo

### ISSUE THREAD

**Issue by marcnoon** [UserLevelUp/OpNode#13]
Currently, the OpNode image logo has a lock on it.  It doesn't relay to new users about the Node and Operations aspects of OpNode.

??? Needs to be replaced with a better Logo.  I'm not a graphics artist or designer and have little or no skill at this.  This project requires someone that does or is at least willing to take a risk. 
<img src="https://repository-images.githubusercontent.com/274567598/c444e080-aac2-48db-9ff6-8d42abc9374c" alt="OpNode Image" />

OpNode means operations that are added to nodes in a treeview.  The operations can be added like extensions.  They may add and subtract items within the parent, such as child nodes.    Types of operations might be added, and removed, XSLT, commands, videos, PowerShell commands, Linux commands, HTML, and accounting.  It's any type of operation you want to act upon the child nodes on that node.

So, an image with a lock is not very expressive. I moded this image from the original image created by someone from 2006 who added the image to pWord.  So, this new image needs to evoke some sort of emotional response that it's something related to this project.  It's something that may be able to automate tasks, keep track of accounting, or perform any number of operations.

**Comment by KaranSinghBisht** [comment]
Hey I would like to work on this, Can you elaborate on the type of logo you are looking for?

**Comment by marcnoon** [comment]
I just added an image via PR.  But after looking at it, it needs to be just the image and not all the extra space, and I was trying to make the p lowercase.   And the ODE to lowercase if possible.

**Comment by marcnoon** [comment]
I'm closing this issue.  The logo Image looks good.  I may make modifications later on.
